---
title: "Adiponectin EWAS - Script 6: Save Full Results"
author: "Lucy Sinke"
output: html_document
---

```{r echo=FALSE}
rm(list=ls())
```

***

# Setup

Load packages

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggpubr)
```

***

```{r}
load("../Adi_Data/Results/Adi_EWAS_Results-Full.Rdata")
```

***

How many CpGs are significant in the base model (6 cells)

```{r}
nrow(adi_results %>% filter(base_meta_padj_fdr <= 0.05))
```

And how many of these are also not heterogenous

```{r}
nrow(adi_results %>% filter(base_meta_padj_fdr <= 0.05 &
                              base_het_i2 < 90))
```

Save

```{r}
top <- adi_results %>% filter(base_meta_padj_fdr <= 0.05 &
                              base_het_i2 < 90)
```

***

# Smoking sensitivity analysis

Inspect

```{r}
top$ext1_meta_padj_fdr <- p.adjust(top$ext1_meta_p,
                                     method='fdr')
nrow(top %>% filter(ext1_meta_padj_fdr <= 0.05))
```

# Cell counts sensitivity analysis

Inspect

```{r}
top$ext3_meta_padj_fdr <- p.adjust(top$ext3_meta_p,
                                     method='fdr')
nrow(top %>% filter(ext3_meta_padj_fdr <= 0.05))
```

# Plots

Smoking

```{r}
ggplot(top, aes(x=base_meta_beta, 
                 y=ext1_meta_beta)) +
  geom_hline(aes(yintercept=0),
             color="#1B2021") +
  geom_vline(aes(xintercept=0),
             color="#1B2021") +
  geom_abline(intercept = 0, slope = 1, color = 'grey40', linetype='dashed') +
  geom_point(color = ifelse(top$ext3_meta_padj_fdr > 0.05, "#c1c0bc", "white"),
             alpha = ifelse(top$ext3_meta_padj_fdr > 0.05, 1, 0)) +
  geom_point(color = ifelse(top$ext1_meta_padj_fdr > 0.05, "#B3AF8F", "white"),
             alpha = ifelse(top$ext1_meta_padj_fdr > 0.05, 1, 0)) +
  geom_point(color = ifelse(top$ext3_meta_padj_fdr <= 0.05 & top$ext1_meta_padj_fdr <= 0.05, "#237194", "white"),
             alpha = ifelse(top$ext3_meta_padj_fdr <= 0.05 & top$ext1_meta_padj_fdr <= 0.05, 1, 0)) +
  stat_cor(data = top %>% filter(ext1_meta_padj_fdr <= 0.05 & ext3_meta_padj_fdr <= 0.05),
           color = "#237194",
           p.accuracy = 0.001, 
           r.accuracy=0.01) +
  xlab('Effect Size (Base)') +
  ylab('Effect Size (Smoking)') +
  ggtitle('') +
  theme(
    axis.text = element_text(
       size=9, 
       color="#1B2021"),
    axis.title = element_text(
      size=11, 
      hjust=0.5, 
      color="#1B2021"),
    plot.title = element_text(
      size=16, 
      hjust=0.5,
      face="bold", 
      color = "#548687"),
    panel.background = element_rect(
      fill="white"),
    panel.border = element_rect(
      color="#1B2021",
      fill=NA),
    panel.grid.major = element_line(
      color="grey95"),
    panel.grid.minor = element_line(
      color="grey95"),
    plot.background = element_rect(
      fill="white"),
    legend.position="none")
```

Plot cells

```{r}
ggplot(top, aes(x=base_meta_beta, 
                 y=ext3_meta_beta)) +
  geom_hline(aes(yintercept=0),
             color="#1B2021") +
  geom_vline(aes(xintercept=0),
             color="#1B2021") +
  geom_abline(intercept = 0, slope = 1, color = 'grey40', linetype='dashed') +
  geom_point(color = ifelse(top$ext1_meta_padj_fdr > 0.05, "#c1c0bc", "white"),
             alpha = ifelse(top$ext1_meta_padj_fdr > 0.05, 1, 0)) +
  geom_point(color = ifelse(top$ext3_meta_padj_fdr > 0.05, "#B3AF8F", "white"),
             alpha = ifelse(top$ext3_meta_padj_fdr > 0.05, 1, 0)) +
  geom_point(color = ifelse(top$ext1_meta_padj_fdr <= 0.05 & top$ext3_meta_padj_fdr <= 0.05, "#237194", "white"),
             alpha = ifelse(top$ext3_meta_padj_fdr <= 0.05 & top$ext3_meta_padj_fdr <= 0.05, 1, 0)) +
  stat_cor(data = top %>% filter(ext1_meta_padj_fdr <= 0.05 & ext3_meta_padj_fdr <= 0.05),
           color = "#237194",
           p.accuracy = 0.001, 
           r.accuracy=0.01) +
  xlab('Effect Size (Base)') +
  ylab('Effect Size (IDOLext)') +
  ggtitle('') +
  theme(
    axis.text = element_text(
       size=9, 
       color="#1B2021"),
    axis.title = element_text(
      size=11, 
      hjust=0.5, 
      color="#1B2021"),
    plot.title = element_text(
      size=16, 
      hjust=0.5,
      face="bold", 
      color = "#548687"),
    panel.background = element_rect(
      fill="white"),
    panel.border = element_rect(
      color="#1B2021",
      fill=NA),
    panel.grid.major = element_line(
      color="grey95"),
    panel.grid.minor = element_line(
      color="grey95"),
    plot.background = element_rect(
      fill="white"),
    legend.position="none")
```

Filter

```{r}
top <- top %>% filter(ext1_meta_padj_fdr <= 0.05 & ext3_meta_padj_fdr <= 0.05)
nrow(top)
```


```{r}
save(top, file='../Adi_Data/Results/AdiTop_2024.Rdata')
```

