---
title: "Bidirectional Manhattan plot"
author: "Lucy Sinke"
date: "6/4/2021"
output: html_document
---

```{r echo=FALSE}
rm(list=ls())
```

Load packages

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(GenomicRanges)
```

Load in data

First we load in the data from the IL-6 EWAS. This is the full results.

```{r}
load("../Adi_Data/Results/Adi_EWAS_Results-Full.Rdata")
load("../Adi_Data/Results/AdiTop_2024.Rdata")
```

We will definitely filter out CpGs with evidence of heterogeneity, so we do this first.

```{r}
# Filter significant with heterogeneity
Adi_results <- adi_results %>% 
  filter(base_meta_padj_fdr > 0.05 |
           (base_meta_padj_fdr <= 0.05 & base_het_i2 < 90))
Adi_top <- top

dim(Adi_results)
dim(Adi_top)
```

Filter out CpGs that were significant but were removed in sensitivity analysis

```{r}
Adi_results <- Adi_results %>% filter(
  base_meta_padj_fdr > 0.05 | 
    (base_meta_padj_fdr <= 0.05 & cpg %in% Adi_top$cpg)
)

dim(Adi_results) 
```

***

Manhattan plots

```{r}
res <- Adi_results %>% 
  dplyr::select(p = base_meta_p, base_meta_beta,
                      chr = cpg_chr_hg19,
                      start = cpg_start_hg19,
                      padj = base_meta_padj_fdr) %>% 
  filter(!is.na(p) & !is.na(chr) & 
           !is.na(start) & 
           !is.na(padj) &
           chr != 'chrX') %>% 
  mutate(chr = as.numeric(sub('chr', '', chr))) %>% 
  mutate(even = ifelse(chr %% 2 == 0, 0, 1),
         p_plus = -log10(p) + 0.5,
         dir = ifelse(base_meta_beta < 0, 'down', 'up')) %>% 
  mutate(p_plus = ifelse(dir == 'down', -p_plus, p_plus)) %>% 
  arrange(chr, start) 

fdr_min <- min(abs((res %>% filter(padj < 0.05))$p_plus))
print(fdr_min)

```

Setup manhattan plot

```{r}
nCHR <- length(unique(res$chr))
nCHR
unique(res$chr)

res$startcum <- NA
s <- 0
gap <- 30000000
nbp <- c()
for (i in unique(res$chr)){
  nbp[i] <- max(res[res$chr == i,]$start) + gap

  res[res$chr == i, "startcum"] <- res[res$chr == i, "start"] + s + gap
  
  #add rows
  res <- rbind(res,
               data.frame(
                 p = NA,
                 base_meta_beta = NA,
                 chr = i,
                 start = nbp[i],
                 padj = NA,
                 even = NA,
                 p_plus = NA,
                 dir = NA,
                 startcum = nbp[i] + s
               ))

  s <- s + nbp[i]
}
nbp

axis.set <- res %>% 
  group_by(chr) %>% 
  summarize(center = (max(startcum) + min(startcum)) / 2)
ylim <- 28
sig <- -log10(0.05)

head(res)
max(res$startcum)
```

Manhattan plot

```{r}
png('../Adi_Data/base_manhattan_circo.png', width = 3000, height = 2000)

ggplot() + 
  geom_hline(yintercept = 0, 
             color = "#362C28", 
             size = 1.5) + 
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = gap, xmax = nbp[1]),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = gap, xmax = nbp[1]),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = gap, xmax = nbp[1]),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 1),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 1))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 1))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 1))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 1))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 1))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 1))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = nbp[1]+gap, xmax = sum(nbp[1:2])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = nbp[1]+gap, xmax = sum(nbp[1:2])),
            fill = 'grey95', color = 'grey90', size=2) + 
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = nbp[1]+gap, xmax = sum(nbp[1:2])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 2),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 2))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 2))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 2))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 2))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 2))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 2))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:2])+gap, xmax = sum(nbp[1:3])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:2])+gap, xmax = sum(nbp[1:3])),
            fill = 'grey95', color = 'grey90', size=2) + 
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:2])+gap, xmax = sum(nbp[1:3])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 3),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 3))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 3))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 3))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 3))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 3))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 3))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:3])+gap, xmax = sum(nbp[1:4])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:3])+gap, xmax = sum(nbp[1:4])),
            fill = 'grey95', color = 'grey90', size=2) + 
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:3])+gap, xmax = sum(nbp[1:4])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 4),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 4))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 4))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 4))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 4))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 4))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 4))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:4])+gap, xmax = sum(nbp[1:5])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:4])+gap, xmax = sum(nbp[1:5])),
            fill = 'grey95', color = 'grey90', size=2) + 
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:4])+gap, xmax = sum(nbp[1:5])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 5),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 5))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 5))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 5))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 5))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 5))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 5))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:5])+gap, xmax = sum(nbp[1:6])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
    geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:5])+gap, xmax = sum(nbp[1:6])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:5])+gap, xmax = sum(nbp[1:6])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 6),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 6))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 6))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 6))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 6))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 6))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 6))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:6])+gap, xmax = sum(nbp[1:7])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:6])+gap, xmax = sum(nbp[1:7])),
            fill = 'grey95', color = 'grey90', size=2) + 
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:6])+gap, xmax = sum(nbp[1:7])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 7),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 7))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 7))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr ==7))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 7))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 7))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 7))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:7])+gap, xmax = sum(nbp[1:8])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:7])+gap, xmax = sum(nbp[1:8])),
            fill = 'grey95', color = 'grey90', size=2) +
    geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:7])+gap, xmax = sum(nbp[1:8])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 8),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 8))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 8))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 8))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 8))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 8))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 8))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:8])+gap, xmax = sum(nbp[1:9])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:8])+gap, xmax = sum(nbp[1:9])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:8])+gap, xmax = sum(nbp[1:9])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 9),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 9))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 9))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 9))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 9))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 9))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 9))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax =0.3,
                xmin = sum(nbp[1:9])+gap, xmax = sum(nbp[1:10])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:9])+gap, xmax = sum(nbp[1:10])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:9])+gap, xmax = sum(nbp[1:10])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 10),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 10))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 10))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 10))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 10))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 10))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 10))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:10])+gap, xmax = sum(nbp[1:11])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:10])+gap, xmax = sum(nbp[1:11])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:10])+gap, xmax = sum(nbp[1:11])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 11),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 11))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 11))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 11))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 11))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 11))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 11))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:11])+gap, xmax = sum(nbp[1:12])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:11])+gap, xmax = sum(nbp[1:12])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:11])+gap, xmax = sum(nbp[1:12])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 12),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 12))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 12))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 12))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 12))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 12))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 12))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:12])+gap, xmax = sum(nbp[1:13])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:12])+gap, xmax = sum(nbp[1:13])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:12])+gap, xmax = sum(nbp[1:13])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 13),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 13))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 13))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 13))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 13))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 13))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 13))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:13])+gap, xmax = sum(nbp[1:14])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:13])+gap, xmax = sum(nbp[1:14])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:13])+gap, xmax = sum(nbp[1:14])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 14),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 14))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 14))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 14))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 14))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 14))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 14))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:14])+gap, xmax = sum(nbp[1:15])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:14])+gap, xmax = sum(nbp[1:15])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:14])+gap, xmax = sum(nbp[1:15])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 15),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 15))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 15))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 15))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 15))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 15))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 15))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:15])+gap, xmax = sum(nbp[1:16])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:15])+gap, xmax = sum(nbp[1:16])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:15])+gap, xmax = sum(nbp[1:16])),
            fill = 'grey95', color = 'grey90', size=2) +
  geom_point(data = res %>% filter(chr == 16),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 16))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 16))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 16))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 16))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 16))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 16))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:16])+gap, xmax = sum(nbp[1:17])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:16])+gap, xmax = sum(nbp[1:17])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:16])+gap, xmax = sum(nbp[1:17])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 17),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 17))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 17))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 17))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 17))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 17))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 17))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:17])+gap, xmax = sum(nbp[1:18])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:17])+gap, xmax = sum(nbp[1:18])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:17])+gap, xmax = sum(nbp[1:18])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 18),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 18))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 18))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 18))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 18))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 18))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 18))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:18])+gap, xmax = sum(nbp[1:19])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:18])+gap, xmax = sum(nbp[1:19])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:18])+gap, xmax = sum(nbp[1:19])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 19),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 19))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 19))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 19))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 19))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 19))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 19))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:19])+gap, xmax = sum(nbp[1:20])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
               xmin = sum(nbp[1:19])+gap, xmax = sum(nbp[1:20])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
               xmin = sum(nbp[1:19])+gap, xmax = sum(nbp[1:20])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 20),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 20))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 20))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 20))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 20))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 20))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 20))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:20])+gap, xmax = sum(nbp[1:21])),
            fill = '#75BBC9', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
               xmin = sum(nbp[1:20])+gap, xmax = sum(nbp[1:21])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
               xmin = sum(nbp[1:20])+gap, xmax = sum(nbp[1:21])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 21),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 21))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 21))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 21))$padj <= 0.05,
                      '#009FBD', 
                      ifelse(
                        (res %>% filter(chr == 21))$padj < 0.05,
                        '#75BBC9', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 21))$padj <= 0.05,
                         '#009FBD', 
                          ifelse(
                            (res %>% filter(chr == 21))$padj < 0.05,
                            '#75BBC9', 'grey80')))  +
  geom_rect(aes(ymin = -0.3, 
                ymax = 0.3,
                xmin = sum(nbp[1:21])+gap, xmax = sum(nbp[1:22])),
            fill = '#F8B9B5', color = '#362C28', size=2)+
  geom_rect(aes(ymin = 0.5, 
                ymax = 17,
                xmin = sum(nbp[1:21])+gap, xmax = sum(nbp[1:22])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_rect(aes(ymin = -0.5, 
                ymax = -17,
                xmin = sum(nbp[1:21])+gap, xmax = sum(nbp[1:22])),
            fill = 'grey95', color = 'grey90', size=2) + 
  geom_point(data = res %>% filter(chr == 22),
             aes(x = startcum,
                 y = p_plus),
                 shape = 21,
             size = ifelse(
                (res %>% filter(chr == 22))$padj < 0.05,
                      6, 
                      ifelse(
                        (res %>% filter(chr == 22))$padj < 0.05,
                         3, 2)),
             color = ifelse(
               (res %>% filter(chr == 22))$padj <= 0.05,
                      '#F07167', 
                      ifelse(
                        (res %>% filter(chr == 22))$padj < 0.05,
                        '#F8B9B5', 'grey80')),
             fill = ifelse(
               (res %>% filter(chr == 22))$padj <= 0.05,
                         '#F07167', 
                          ifelse(
                            (res %>% filter(chr == 22))$padj < 0.05,
                            '#F8B9B5', 'grey80')))  +
  scale_x_continuous(label = axis.set$chr, 
                     breaks = axis.set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-18, 18)) +
  labs(x = '', 
       y = "") + 
  ggtitle('',
          subtitle = '') +
  theme( 
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_rect(fill = 'white', 
                                    color = 'white'),
    plot.background = element_rect(fill = '#f2f2f2',
                                   color='#f2f2f2'),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.y = element_text(size = 24),
    axis.text.x = element_text(size = 24, margin=margin(b=20)),
    axis.title = element_text(size=18),
    plot.title = element_text(size = 24, 
                              hjust=0.5),
    plot.subtitle = element_text(size = 18, 
                                 hjust=0.5))
dev.off()
```
